# tasks file for php
- name: kill all apache2 process
  apt:
     name: apache2
     state: absent

- name: install nginx
  apt:
    name: nginx
    state: present

- name: start nginx
  service: 
      name: nginx
      state: started

- name: update cache
  apt:
    update_cache: yes

- name: installing all dependencies
  apt: 
   name: "{{item}}"
   state: present
  with_items:
       - php8.1
       - php8.1-fpm
       - php8.1-mysql
       - mysql-server
       - mysql-client
       - python3-dev
       - python3-mysqldb 
       - libmysqlclient-dev

- name: replace the file default at /etc/nginx/sites-available
  copy:
      src: ~/LEMP_ANSIBLE
      dest: /etc/nginx/sites-available/.
      force: yes
      owner: root
      group: root

